export interface Antrag {
  antragId: number
  antragWorktime: number
  antragPortal: number
  antragAdminUserId: number
  adminUserName: string
  antragFirma: string
  antragKundeVorname: string
  antragKundeName: string
  adminUserName: string
  userId: number
  projektId: string
  antragStatus: number
}

export interface AntragFull {
  antragId: number
  projektId: string
  antragAdminUserId: number
  userId: number
  bzaId: string
  antragStatus: number
  antragStatusAuftrag: number
  antragStatusBestaetigung: number
  antragStatusBestaetigungMail: number
  antragStatusRechnung: number
  antragStatusRechnungPayid: number
  antragStatusBza: number
  antragStatusBzaDatei: number
  antragStatusBzaEmail: number
  antragStatusBescheid: number
  antragStatusBescheidDatei: number
  antragStatusBescheidFrist: number
  antragStatusFristEmailFirma: number
  antragStatusFristEmailKunde: number
  antragStatusBndStart: number
  antragStatusBndUnternehmer: number
  antragStatusBndEmail: number
  antragStatusBnd: number
  antragStatusBndDatei: number
  antragBndId: string
  antragErklaerungDateiId: number
  antragVdzDateiId: number
  antragJazDateiId: number
  antragRechnungenStatus: number
  antragRechnungFrist: number
  antragRechnungen: string
  antragBilderStatus: number
  antragStatusAuszahlung: number
  antragFirma: string
  antragFirmaAnsprechpartner: string
  antragFirmaStrasse: string
  antragFirmaHausnummer: string
  antragFirmaPLZ: string
  antragFirmaOrt: string
  antragFirmaTelefon: string
  antragFirmaEmail: string
  antragKundeVorname: string
  antragKundeName: string
  antragKundeFirma: string
  antragKundeVorsteuerberechtigung: string
  antragKundeWirtschaftlichezwecke: string
  antragKundeStrasse: string
  antragKundeHausnummer: string
  antragKundePLZ: string
  antragKundeOrt: string
  antragKundeTelefon: string
  antragKundeEmail: string
  antragKundeAbweichendesObjektStatus: string
  antragKundeAbweichendesObjekt: string
  antragObjektBaujahr: string
  antragObjektFlaeche: number
  antragObjektArt: number
  antragObjektEigentuemer: number
  antragObjektWohneinheiten: number
  antragObjektSelbstgenutzt: number
  antragObjektBetroffeneWE: number
  antragObjektWaermenetz: string
  antragKundeEinkommensbonus: string
  antragObjektAlterheizung: string
  antragObjektHeizlast: string
  antragObjektAlteHeizung: number
  antragObjektArtalteHeizung: number
  antragObjektSolarthermieStatus: string
  antragObjektSolarthermie: string
  antragObjektSolarthermieAnlageStatus: string
  antragObjektBiomasseStatus: string
  antragObjektBrennstoffzelleStatus: string
  antragObjektWasserstoffStatus: string
  antragObjektInnovativeStatus: string
  antragObjektGebaeudenetzStatus: string
  antragObjektWaermenetzStatus: string
  antragObjektWaermepumpeStatus: string
  antragObjektWaermepumpeBetriebsweise: number
  antragObjektSystemtemperatur: string
  antragObjektWpNennleistung: string
  antragObjektWPWaermequelle: number
  antragObjektBiomassePufferspeicherStatus: string
  antragObjektBiomassePuffergroesse: string
  antragObjektPuffergroesse: string
  antragObjektTechnischeAnforderungen: string
  antragObjektTechnischeAnforderungen2: string
  antragObjektTechnischeAnforderungen3: string
  antragProjektVertragStatus: string
  antragVertragDateiId: number
  antragKostenSolar: string
  antragAuftrag: string
  antragDatenschutz: string
  antragErklaerung: string
  antragHeizungSolarArt: number
  antragHeizungSolarFlaeche: string
  antragHeizungBiomasse1: string
  antragHeizungBiomasse2: string
  antragHeizungBiomasse3: string
  antragHeizungBiomasse4: string
  antragObjektBiomasseNennleistung: string
  antragKostenBiomasse: string
  antragKostenWaermepumpe: string
  antragObjektWaermepumpeJAZ: string
  antragObjektWPBeheizung: number
  antragObjektWaermepumpeGroesse1: string
  antragObjektWaermepumpeGroesse2: string
  antragKostenBrennstoffzelle: string
  antragObjektBrennstoffzelleNennleistung: string
  antragKostenWasserstoff: string
  antragObjektWasserstoffNennleistung: string
  antragObjektInnovativeNennleistung: string
  antragKostenInnovative: string
  antragObjektGebaeudenetzNennleistung: string
  antragKostenGebaeudenetz: string
  antragObjektWaermenetzNennleistung: string
  antragKostenWaermenetz: string
  antragObjektWaermepumpeKaeltemittel: string
  antragObjektBonusEmission: string
  antragSecondaryMails: string
  antragPortal: number
  antragWorktime: number
  antragNotiz: string
  adminUser: AdminUserName
}

export interface AdminUserName{
adminUserName: string
}

export interface AntragState {
  antrag: AntragFull
  antragsList: Antrag[]
  errorMessage?: string
  status: string
}
